{{- if .Values.clusterroles.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anarchy-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - anarchy.gpte.redhat.com
  resources:
  - anarchyactions
  - anarchycommunes
  - anarchygovernors
  - anarchyrunners
  - anarchyruns
  - anarchysubjects
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kopf.dev
  resources:
  - kopfpeerings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
