# Anarchy Development

Anarchy development is primarily aimed at development within an OpenShift cluster.
Any recent version of OpenShift will be suitable.

Prior to beginning Anarchy development, the Anarchy Custom Resource Definitions (CRDs) must be installed.
If Anarchy is not already installed on your cluster, you can install them with:

----------------------------
oc apply -Rf helm/crds/
----------------------------

Anarchy development can be performed in the `odo` OpenShift developer CLI or building with OpenShift build configs.
Use of `odo` is recommended for fast iterative development, but all changes should be tested against a build with Anarchy components running in separate deployments before opening a pull request.

Anarchy is build on top of https://github.com/redhat-cop/containers-quickstarts/tree/master/build-s2i-python-kopf[Python Kopf source-to-image].
Kopf requires the CustomResourceDefinition `kopfpeerings.kopf.dev` to govern operations between pods.
If this CRD is not already available in the cluster it and should be applied with:

---------------------------------
oc apply -f kopfpeerings.crd.yaml
---------------------------------

Steps described here for building and testing Anarchy assume you have already installed the Anarchy custom resource definitions and cluster roles.

## Using odo

The `odo` developer CLI can be installed as described in the OpenShift documentation:

https://docs.openshift.com/container-platform/latest/cli_reference/developer_cli_odo/installing-odo.html[Installing odo]

To run Anarchy with `odo`, first create the `python-kopf` ImageStream definition in the `openshift` namespace using the Red Hat Community of Practice containers-quickstarts repository.

--------------------------------------------------------------------------------
oc apply -f https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/master/build-s2i-python-kopf/imagestream.yaml
--------------------------------------------------------------------------------

Use `odo create` to setup configuration for beginning work on Anarchy:

-----------------------------------------------------------------------------
odo create python-kopf anarchy
-----------------------------------------------------------------------------

Use `odo push` to create an `anarchy-app` DeploymentConfig and Service.

--------
odo push
--------

At the time of this writing `odo` cannot create service accounts and so the `anarchy` service account must be created separately after initial push.

--------------------------------
oc create serviceaccount anarchy
--------------------------------

The `anarchy` service account will at least need

-----------------------------------------------------------------------------
oc policy add-role-to-user anarchy --rolebinding-name=anarchy -z anarchy
-----------------------------------------------------------------------------

-----------------------------------------------------------------------------
oc patch dc/anarchy-app \
--patch '{"spec":{"template":{"spec":{"serviceAccountName":"anarchy"}}}}'
-----------------------------------------------------------------------------

-----------------------------------------------------------------------------
odo push --force-build
-----------------------------------------------------------------------------

. Run test playbook
+
----
ansible-playbook test/odo-playbook.yaml
----

== Building an Anarchy Container Image

=== OpenShift

Create the Anarchy BuildConfig and ImageStream using the provided template:

---------------------------------------------------------
oc process -f build-template.yaml --local | oc apply -f -
---------------------------------------------------------

Build the anarchy image from local source:

---------------------------------------
oc start-build -wF anarchy --from-dir=.
---------------------------------------

Deploy new Anarchy image from build with helm template:

--------------------------------------------------------------------------------
helm template helm/ \
--set=envVars.CLEANUP_INTERVAL="10" \
--set=image.repository=$(oc get imagestream anarchy -o jsonpath='{.status.tags[?(@.tag=="latest")].items[0].dockerImageReference}') \
| oc apply -f -
--------------------------------------------------------------------------------

Run test playbook

-----------------------------------
ansible-playbook test/playbook.yaml
-----------------------------------
