---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cakephp-ex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: anarchy-operator
  namespace: anarchy-operator
- kind: ServiceAccount
  name: anarchy-runner-default
  namespace: anarchy-operator
