{{- if .Values.deploy }}
{{- $namespace := .Values.namespace }}
{{- range $runnerName, $runner := $namespace.runners | default $.Values.runners }}
{{- $serviceAccountName := (hasKey $runner "serviceAccountName") | ternary $runner.serviceAccountName (printf "%s-runner-%s" (include "anarchy.name" $) $runnerName) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ $namespace.name }}
---
apiVersion: anarchy.gpte.redhat.com/v1
kind: AnarchyRunner
metadata:
  name: {{ $runnerName }}
  namespace: {{ $namespace.name }}
spec:
{{- if $runner.consecutiveFailureLimit }}
  consecutiveFailureLimit: {{ $runner.consecutiveFailureLimit }}
{{- end }}
{{- if $runner.maxReplicas }}
  maxReplicas: {{ $runner.maxReplicas }}
{{- end }}
{{- if $runner.minReplicas }}
  minReplicas: {{ $runner.minReplicas }}
{{- else }}
  minReplicas: 1
{{- end }}
  podTemplate:
    spec:
      containers:
      - name: runner
        resources:
          {{- toYaml $runner.resources | nindent 10 }}
      serviceAccountName: {{ $serviceAccountName }}
{{- if $runner.runLimit }}
  runLimit: {{ $runner.runLimit }}
{{- end }}
{{- if $runner.scaleUpDelay }}
  scaleUpDelay: {{ $runner.scaleUpDelay }}
{{- end }}
{{- if $runner.scaleUpThreshold }}
  scaleUpThreshold: {{ $runner.scaleUpThreshold }}
{{- end }}
{{- if $runner.scalingCheckInterval }}
  scalingCheckInterval: {{ $runner.scalingCheckInterval }}
{{- end }}
{{- end }}
{{- end }}
