{{- if .Values.deploy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anarchy.apiName" . }}
  namespace: {{ include "anarchy.namespaceName" . }}
  labels:
    {{- include "anarchy.labels" . | nindent 4 }}
    app.kburenetes.io/component: operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "anarchy.apiComponentLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "anarchy.apiComponentLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "anarchy.serviceAccountName" . }}
      containers:
      - name: api
        env:
        - name: ANARCHY_COMPONENT
          value: api
        - name: ANARCHY_SERVICE
          value: {{ include "anarchy.name" . }}
        {{- if .Values.ingress.enabled }}
        - name: CALLBACK_BASE_URL
          value: https://{{ (index .Values.ingress.hosts 0).host }}
        {{- end }}
        {{- if .Values.image.repository | contains ":" }}
        image: {{ .Values.image.repository }}
        {{- else }}
        image: {{ .Values.image.repository }}:v{{ .Chart.AppVersion }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
