{{- if and .Values.deploy (or .Values.namespace.create .Values.namespaces) }}
{{- range $namespace := .Values.namespaces | default (list .Values.namespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace.name }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "anarchy.labels" $ | nindent 4 }}
{{- end }}
{{- end }}
