{{- if and .Values.deploy .Values.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "anarchy.labels" $ | nindent 4 }}
{{- end }}
