{{- if and .Values.deploy .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anarchy.serviceAccountName" $ }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "anarchy.labels" $ | nindent 4 }}
{{- end }}
