{{- if and .Values.deploy .Values.serviceAccount.create -}}
{{- range $namespace := .Values.namespaces | default (list .Values.namespace) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anarchy.serviceAccountName" $ }}
  namespace: {{ $namespace.name }}
  labels:
    {{- include "anarchy.labels" $ | nindent 4 }}
{{- end }}
{{- end }}
