# permissions for end users to view anarchycommunes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-anarchycommune-view
rules:
- apiGroups:
  - anarchy.gpte.redhat.com
  resources:
  - anarchycommunes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - anarchy.gpte.redhat.com
  resources:
  - anarchycommunes/status
  verbs:
  - get
