---
kind: ClusterRole
apiVersion: v1
metadata:
  name: anarchy-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - anarchy.gpte.redhat.com
  resources:
  - anarchygovernors
  - anarchyrunners
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
