---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: anarchycommunes.anarchy.gpte.redhat.com
spec:
  group: anarchy.gpte.redhat.com
  names:
    kind: AnarchyCommune
    listKind: AnarchyCommuneList
    plural: anarchycommunes
    singular: anarchycommune
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: >-
          AnarchyCommune is the Schema for the anarchycommunes API
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          envVars:
            type: object
            additionalProperties:
              type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*[a-z0-9A-Z])?$
          spec:
            type: object
            description: >-
              Definition of how to deploy Anarchy for the commune.
            properties:
              runners:
                description: >-
                  AnarchyRunner configuration.
                type: object
                additionalProperties:
                  type: object
                  properties:
                    consecutiveFailureLimit:
                      type: integer
                    maxReplicas:
                      type: integer
                    minReplicas:
                      type: integer
                    resources:
                      type: object
                      properties:
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                    runLimit:
                      type: integer
                    scaleUpDelay:
                      type: string
                    scaleUpThreshold:
                      type: integer
                    scalingCheckInterval:
                      type: string
          status:
            description: Status defines the observed state of AnarchyCommune
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              resources:
                type: array
                items:
                  type: object
                  required:
                  - apiVersion
                  - kind
                  - name
                  - uid
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    uid:
                      type: string
