{{- if .Values.anarchyDeploy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anarchy.name" . }}
  labels:
    {{- include "anarchy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "anarchy.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "anarchy.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "anarchy.serviceAccountName" . }}
      containers:
      - name: manager
        env:
        - name: ANARCHY_SERVICE
          value: {{ include "anarchy.name" . }}
        {{- range $k, $v := .Values.envVars }}
        - name: {{ $k }}
          value: {{ $v }}
        {{- end }}
        {{- if .Values.image.repository | contains ":" }}
        image: {{ .Values.image.repository }}
        {{- else }}
        image: {{ .Values.image.repository }}:v{{ .Chart.AppVersion }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
