{{- if .Values.anarchyDeploy -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "anarchy.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anarchy
subjects:
- kind: ServiceAccount
  name: {{ include "anarchy.serviceAccountName" . }}
{{- end }}
