{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anarchy.serviceAccountName" . }}
  labels:
{{ include "anarchy.labels" . | nindent 4 }}
{{- end -}}
